modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="naruto_block"
version="1.0.0"
displayName="Naruto Block"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="User, MCreator"

[[dependencies.naruto_block]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




